# not using sudo
sudo: false

language: node_js
node_js:
- lts/*

# setup the travis token
env:
  global:
    - secure: jWTxnnLGmoM+j3148tIF2SJMEyub2j9kmR15vEKVeP6BbUvNgWH9jTSwf6Ddv3qjbAb3D8p9nhYBOZgRub1stwjWCH+DS17AoKFeRVj4Q8Sf0XBHGzJbn0FkstilVmGv3Zr/FVmDSEm1xSSHanWCUQX0uH9r/XB8z7khp4pLryo=

# greenkeeper lock file
before_install: yarn global add greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload

# main
script:
- yarn run lint
- yarn run test-ci --verbose
- yarn run build

after_success:
# send coverage to coveralls
- grunt coveralls
# update gh-page only if not a pull request and if branch master or develop
- if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_BRANCH" == "develop" ]; then
      chmod +x ./resources/scripts/update-gh-pages.sh; "./resources/scripts/update-gh-pages.sh";
    else echo "Not deploying artifacts for branch $TRAVIS_BRANCH"; fi
  else echo "Not deploying artifacts for pull request"; fi
